name: Deploy to Dev

on:
    workflow_dispatch:
#    push:
#        branches:
#            - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: Azure/arm-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RG }}
        template: /path/to/bicep-template.bicep
        parameters: /path/to/parameters.json
        deployment-mode: Incremental