jobs:
        job1:
                runs-on: ubuntu-latest
                steps:
                        - name: Step 1
                            run: echo "step 1"
                        - name: Step 2
                            run: echo "step 2"
