# generate a workflow that triggers manually called "job1" that runs on ubuntu-latest and has two steps:
# step 1: echo "step 1"
# step 2: echo "step 2"
name: First Workflow

on:
    workflow_dispatch:
    issues:
        types: [opened]

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: 'Step1'
              run: echo 'step 1'

            - name: "Step2"
              run: echo "step 2"

    job2:
        needs: job1
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: mscoutermarsh/cowsays-action@master
              with:
                    text: "Go, team 14!"
                    color: "green"
